// Generated by CoffeeScript 1.6.3
(function() {
  var ChromeClassicNewTab;

  ChromeClassicNewTab = (function() {
    var AppItem, AppsList, BookmarkItem, BookmarksBar, BookmarksList, BookmarksPopup, Footer, _class, _class1, _class2, _class3, _ref, _ref1, _ref2, _ref3;

    function ChromeClassicNewTab($viewport) {
      this.$viewport = $viewport;
      this.bookmarksBar = new BookmarksBar();
      this.bookmarksBar.render(this.$viewport);
      this.appsList = new AppsList();
      this.appsList.render(this.$viewport);
      this.footer = new Footer();
      this.footer.render(this.$viewport);
    }

    BookmarksBar = (function() {
      function BookmarksBar() {
        var _this = this;
        this.bookmarksLoaded = new RSVP.Promise(function(resolve, reject) {
          return chrome.bookmarks.getChildren("1", function(bookmarks) {
            _this.bookmarks = bookmarks;
            return resolve(_this.bookmarks);
          });
        });
      }

      BookmarksBar.prototype.render = function($viewport) {
        var _this = this;
        this.$viewport = $viewport;
        this.$el = document.createElement("div");
        this.$el.id = "bookmarks-bar";
        this.$viewport.appendChild(this.$el);
        return this.bookmarksLoaded.then(function() {
          var bookmarksList, otherBookmarksList;
          bookmarksList = new BookmarksList(_this.bookmarks);
          bookmarksList.render(_this.$el);
          otherBookmarksList = new BookmarksList([
            {
              id: "2",
              title: "Other Bookmarks"
            }
          ]);
          otherBookmarksList.render(_this.$el);
          return otherBookmarksList.$el.className += " other-bookmarks";
        });
      };

      return BookmarksBar;

    })();

    BookmarksList = (function() {
      function BookmarksList() {
        _ref = _class.apply(this, arguments);
        return _ref;
      }

      _class = (function(bookmarks) {
        this.bookmarks = bookmarks;
      });

      BookmarksList.prototype.render = function($viewport) {
        var bookmark, bookmarkItem, _i, _len, _ref1;
        this.$viewport = $viewport;
        this.$el = document.createElement("ul");
        this.$el.className = "bookmarks-list clearfix";
        _ref1 = this.bookmarks;
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          bookmark = _ref1[_i];
          bookmarkItem = new BookmarkItem(bookmark);
          bookmarkItem.delegate = this;
          bookmarkItem.render(this.$el);
        }
        return this.$viewport.appendChild(this.$el);
      };

      BookmarksList.prototype.BookmarkItemDidClickFolder = function(bookmarkItem) {
        var _this = this;
        return chrome.bookmarks.getChildren(bookmarkItem.bookmark.id, function(bookmarks) {
          var popup;
          popup = new BookmarksPopup(bookmarks, {
            region: "bottom"
          });
          return popup.render(bookmarkItem.$el);
        });
      };

      return BookmarksList;

    })();

    BookmarksPopup = (function() {
      function BookmarksPopup() {
        _ref1 = _class1.apply(this, arguments);
        return _ref1;
      }

      _class1 = (function(bookmarks, options) {
        this.bookmarks = bookmarks;
        this.options = options != null ? options : {};
      });

      BookmarksPopup.prototype.render = function($target) {
        var bookmark, bookmarkItem, _i, _len, _ref2;
        this.$target = $target;
        this.$el = document.createElement("ul");
        this.$el.className = "bookmarks-list";
        _ref2 = this.bookmarks;
        for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
          bookmark = _ref2[_i];
          bookmarkItem = new BookmarkItem(bookmark);
          bookmarkItem.delegate = this;
          bookmarkItem.render(this.$el);
        }
        this.flowtip = new FlowTip(_.extend(this.options, {
          hasTail: false
        }));
        this.flowtip.setTooltipContent(this.$el);
        this.flowtip.setTarget(this.$target);
        return this.flowtip.show();
      };

      return BookmarksPopup;

    })();

    BookmarkItem = (function() {
      function BookmarkItem() {
        _ref2 = _class2.apply(this, arguments);
        return _ref2;
      }

      _class2 = (function(bookmark) {
        this.bookmark = bookmark;
      });

      BookmarkItem.prototype.render = function($viewport) {
        var $icon, $label, $link,
          _this = this;
        this.$viewport = $viewport;
        this.$el = document.createElement("li");
        this.$el.className = "bookmark-item";
        if (!this.bookmark.url) {
          this.$el.className += " folder-item";
        }
        $link = document.createElement("a");
        $icon = document.createElement("img");
        $label = document.createElement("span");
        $link.className = "clearfix";
        if (this.bookmark.url) {
          $link.setAttribute("href", this.bookmark.url);
        } else {
          $link.addEventListener("click", function() {
            var _ref3;
            return (_ref3 = _this.delegate) != null ? typeof _ref3.BookmarkItemDidClickFolder === "function" ? _ref3.BookmarkItemDidClickFolder(_this) : void 0 : void 0;
          }, false);
        }
        $icon.setAttribute("src", this.faviconURL());
        $icon.setAttribute("width", "16");
        $icon.setAttribute("height", "16");
        $label.innerHTML = this.bookmark.title.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
        $link.appendChild($icon);
        $link.appendChild($label);
        this.$el.appendChild($link);
        return this.$viewport.appendChild(this.$el);
      };

      BookmarkItem.prototype.faviconURL = function() {
        if (this.bookmark.url) {
          return "chrome://favicon/" + this.bookmark.url;
        } else {
          return "images/folder.png";
        }
      };

      return BookmarkItem;

    })();

    AppsList = (function() {
      function AppsList() {
        var _this = this;
        this.appsLoaded = new RSVP.Promise(function(resolve, reject) {
          return chrome.management.getAll(function(extensions) {
            var extension;
            _this.apps = (function() {
              var _i, _len, _results;
              _results = [];
              for (_i = 0, _len = extensions.length; _i < _len; _i++) {
                extension = extensions[_i];
                if (extension.enabled && extension.isApp) {
                  _results.push(extension);
                }
              }
              return _results;
            })();
            return resolve(_this.apps);
          });
        });
        window.addEventListener("resize", function() {
          return _this.repositionList();
        });
      }

      AppsList.prototype.render = function(viewport) {
        var _this = this;
        this.viewport = viewport;
        this.el = document.createElement("div");
        this.el.id = "apps-wrapper";
        this.list = document.createElement("ul");
        this.list.id = "apps";
        this.list.className = "clearfix";
        this.el.appendChild(this.list);
        this.viewport.appendChild(this.el);
        return this.appsLoaded.then(function() {
          _this.renderApps();
          return _this.repositionList();
        });
      };

      AppsList.prototype.renderApps = function() {
        var app, appItem, _i, _len, _ref3, _results;
        this.apps.unshift({
          name: "Store",
          url: "https://chrome.google.com/webstore",
          icons: [
            {
              size: 128,
              url: "images/web-store_128.png"
            }
          ]
        });
        _ref3 = this.apps;
        _results = [];
        for (_i = 0, _len = _ref3.length; _i < _len; _i++) {
          app = _ref3[_i];
          appItem = new AppItem(app);
          _results.push(appItem.render(this.list));
        }
        return _results;
      };

      AppsList.prototype.repositionList = function() {
        return this.list.style.marginTop = ((this.el.clientHeight - this.list.clientHeight) / 3) + "px";
      };

      return AppsList;

    })();

    AppItem = (function() {
      function AppItem() {
        _ref3 = _class3.apply(this, arguments);
        return _ref3;
      }

      _class3 = (function(app) {
        this.app = app;
      });

      AppItem.prototype.render = function(viewport) {
        var icon, label, link,
          _this = this;
        this.viewport = viewport;
        this.el = document.createElement("li");
        this.el.className = "app-item";
        link = document.createElement("a");
        icon = document.createElement("img");
        label = document.createElement("span");
        link.className = "clearfix";
        if (this.app.id) {
          link.addEventListener("click", function() {
            return chrome.management.launchApp(_this.app.id, function() {
              return window.close();
            });
          }, false);
        } else if (this.app.url) {
          link.setAttribute("href", this.app.url);
        }
        icon.setAttribute("src", this.iconURL());
        icon.setAttribute("width", "128");
        icon.setAttribute("height", "128");
        label.innerHTML = this.app.name.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
        link.appendChild(icon);
        link.appendChild(label);
        this.el.appendChild(link);
        return this.viewport.appendChild(this.el);
      };

      AppItem.prototype.iconURL = function() {
        var icon, largestURL, size, _i, _len, _ref4;
        size = 0;
        largestURL = null;
        _ref4 = this.app.icons;
        for (_i = 0, _len = _ref4.length; _i < _len; _i++) {
          icon = _ref4[_i];
          if (icon.size > size) {
            size = icon.size;
            largestURL = icon.url;
          }
        }
        return largestURL;
      };

      return AppItem;

    })();

    Footer = (function() {
      function Footer() {}

      Footer.prototype.render = function($viewport) {
        var img, storeLink, storeLogo, storeTitle, title;
        this.$viewport = $viewport;
        this.el = document.createElement("div");
        this.el.id = "footer";
        img = document.createElement("img");
        img.className = "chrome-logo";
        img.setAttribute("src", "images/chrome.png");
        img.setAttribute("width", "28");
        img.setAttribute("height", "28");
        this.el.appendChild(img);
        title = document.createElement("h1");
        title.innerHTML = "chrome";
        this.el.appendChild(title);
        storeLink = document.createElement("a");
        storeLink.className = "web-store";
        storeLink.setAttribute("href", "https://chrome.google.com/webstore");
        storeTitle = document.createElement("span");
        storeTitle.innerHTML = "Web Store";
        storeLink.appendChild(storeTitle);
        storeLogo = document.createElement("img");
        storeLogo.setAttribute("src", "images/web-store_20.png");
        storeLogo.setAttribute("width", "20");
        storeLogo.setAttribute("height", "20");
        storeLink.appendChild(storeLogo);
        this.el.appendChild(storeLink);
        return this.$viewport.appendChild(this.el);
      };

      return Footer;

    })();

    return ChromeClassicNewTab;

  })();

  window.onload = function() {
    var classicNewTab;
    return classicNewTab = new ChromeClassicNewTab(document.body);
  };

}).call(this);
